name: Project

on: 
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USER }}/project
          tags: ${{ github.sha }}, latest